### ISSUE TITLE
Should the cipher-object be created with an IV?

### ISSUE THREAD

**Issue by letharion** [HainaLi/horcrux_password_manager#1] opened 2017-06-19 14:34 UTC
I'll start by saying I'm not a crypto expert by any means.

However, it was pointed out on HN that the encrypt function doesn't use an IV when initializing the cipher object, and the [node documention](https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password) explicitly says 
> "In line with OpenSSL's recommendation to use pbkdf2 instead of EVP_BytesToKey it is recommended that developers derive a key and IV on their own using crypto.pbkdf2() and to use crypto.createCipheriv() to create the Cipher object."

Since the official docs appears to recommend against `crypto.createCipher()` I figured it was worth bringing up.

**Comment by iangcarroll** [comment] 2017-06-19 16:25
To be clear: if two ciphertexts use the same IV across ciphertexts with CTR, you basically have no encryption, as C1^C2=P1^P2, where Cs are the ciphertexts and Ps are the plaintexts.

**Comment by gradientsky** [comment] 2017-06-19 22:14
IV doesn't have to be secure, but it has to be securely random on every re-encryption.

**Comment by stouset** [comment] 2017-06-20 00:01
@sgdread Technically for CTR mode, it only needs to be *unique* and not necessarily random or unpredictable — it's a nonce, not an IV.

**Comment by HainaLi** [comment] 2017-06-21 02:15
This is an important implementation issue! I'm currently traveling and will try to push a fix out asap.

**Comment by HainaLi** [comment] 2017-06-26 19:29
Thanks for your input. The issue is fixed with ef8bc9aed55dba3b320d9ec441946091f273723b. 

We also changed the block cipher mode of operation to GCM. The encryption (and decryption code) are moved to utils.js line 19.

**Closed as completed by HainaLi** 2017-06-26 19:29 UTC
Labels: bug
